#apiVersion: v1
#kind: Namespace
#metadata:
#  name: flask-cluster
---
apiVersion: apps/v1
kind: Deployment
metadata:
        name: flask-deployment
spec:
  selector:
    matchLabels:
      app: flask
  replicas: 3     # 3个副本
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: 88382078/flask:v2.0.0
#          resources:
#            requests:
#              cpu: 3
#              memory: 50M
#            limits:
#              cpu: 5
#              memory: 100M
          env:
            - name: imageVersion
              value: v2
          ports:
          - containerPort: 8080
#          readinessProbe:
#            periodSeconds: 1  #定义一个就绪探针并每隔1s执行一次
#            httpGet:
#              path: /initdb
#              port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: flask
  labels:
    app: flask
spec:
  ports:
  - port: 8080
    name: http
    protocol: TCP
    targetPort: 8080

  selector:
    app: flask

