apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
        name: php-apache
spec:
  scaleTargetRef:
    apiVersion: app/v1
    kind: Deployment
    name: php-apache
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50